####################################################
#
# Web访问端口号 约定：8088
#
####################################################
server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB

####################################################
#
# 配置数据源信息
#
####################################################
spring:
  datasource:                                   # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource    # 数据源类型，HikariCP
    driver-class-name: com.mysql.jdbc.Driver    # mysql 驱动
    url: jdbc:mysql://localhost:3306/foodie-shop?useUnicode=true&characterEncoding=UTF-8&autoReconnect
    username: root
    password: root
  hikari:
    connection-timeout: 30000     # 等待连接池分配连接的最大时长（毫秒），超过时长还无连接则发生 SQLException，默认：30秒
    minimum-idle: 5               # 最小连接数
    maximum-pool-size: 20         # 最大连接数
    auto-commit: true             # 自动提交
    idle-timeout: 600000          # 连接超时的最大时长（毫秒），超时则被释放（retired），默认：10分钟
    pool-name: DataSourceHikariCP # 连接池名称
    max-lifetime: 1800000         # 连接的生命时长（毫秒）超时而没有被使用则释放（retired），默认：30分钟
    connection-test-query: SELECT 1

####################################################
#
# MyBatis 配置
#
####################################################
mybatis:
  type-aliases-package: org.alanhou.pojo    # 所有 POJO 类所在包路径
  mapper-locations: classpath:mapper/*.xml  # mapper映射文件
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

####################################################
#
# MyBatis mapper配置
#
####################################################
mapper:
  mappers: org.alanhou.my.mapper.MyMapper
  not-empty: false # 在进行数据库操作时，判断表达式username != null,是否追加 username! = ""
  identity: MYSQL